<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-02-14 03:45
=======
# Generated by Django 6.0.2 on 2026-02-14 23:06
>>>>>>> 721dea6db0a42497a6757770dea36b37d0a335db

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_application_resume_file_alter_application_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='applied', max_length=20),
        ),
    ]
