# Generated by Django 6.0.2 on 2026-02-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0004_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="employer_viewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="employer_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
