# Generated by Django 6.0.2 on 2026-02-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0005_application_employer_viewed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="archived_by_applicant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="archived_by_employer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
