# Generated by Django 6.0.2 on 2026-02-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0006_application_archive_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="auto_rejected_for_timeout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
