# Generated by Django 6.0.2 on 2026-02-13

import decimal
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('jobposts', '0004_jobpost_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(decimal.Decimal('-90')), django.core.validators.MaxValueValidator(decimal.Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(decimal.Decimal('-180')), django.core.validators.MaxValueValidator(decimal.Decimal('180'))])),
                ('job_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_location', to='jobposts.jobpost')),
            ],
            options={
                'ordering': ['job_post_id'],
            },
        ),
    ]
