# Generated by Django 6.0.2 on 2026-02-13

from django.db import migrations, models


def copy_address_to_line_1(apps, schema_editor):
    OfficeLocation = apps.get_model('map', 'OfficeLocation')
    for office in OfficeLocation.objects.exclude(address=''):
        office.address_line_1 = office.address
        office.save(update_fields=['address_line_1'])


class Migration(migrations.Migration):
    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(copy_address_to_line_1, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='officelocation',
            name='address',
        ),
    ]
