# Generated by Django 6.0.2 on 2026-02-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('APPLICANT', 'Job Applicant'), ('EMPLOYEE', 'Employee')], default='APPLICANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
