# Generated by Django 6.0.2 on 2026-02-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_account_type_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('APPLICANT', 'Job Applicant'), ('EMPLOYER', 'Employer')], default='APPLICANT', max_length=20),
        ),
    ]
