# Generated by Django 6.0.2 on 2026-02-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_privacy'),
        ('accounts', '0003_profile_company_description_profile_company_name_and_more'),
    ]

    operations = [
    ]
