# Generated by Django 6.0.2 on 2026-02-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260212_2226'),
        ('accounts', '0004_merge_profile_branches'),
    ]

    operations = [
    ]
