# Generated by Django 6.0.2 on 2026-02-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260213_1637'),
        ('accounts', '0004_merge_20260213_2358'),
    ]

    operations = [
    ]
