# Generated by Django 6.0.2 on 2026-02-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260214_1118'),
        ('accounts', '0007_profile_profile_picture'),
    ]

    operations = [
    ]
