# Generated by Django 6.0.2 on 2026-02-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260213_1940'),
        ('accounts', '0008_merge_20260215_0349'),
    ]

    operations = [
    ]
