# Generated by Django 6.0.2 on 2026-02-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260215_0132'),
        ('accounts', '0010_profile_created_at_profilelink_created_at'),
    ]

    operations = [
    ]
