# Generated by Django 6.0.2 on 2026-02-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_created_at_profilelink_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_typing_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
