# Generated by Django 6.0.2 on 2026-02-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260213_1108'),
        ('accounts', '0011_merge_20260217_1555'),
    ]

    operations = [
    ]
