# Generated by Django 6.0.2 on 2026-02-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20260217_1555'),
        ('accounts', '0011_profile_is_typing_profile_last_activity_and_more'),
    ]

    operations = [
    ]
