# Generated by Django 6.0.2 on 2026-02-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260217_1750'),
        ('accounts', '0012_merge_20260217_2257'),
    ]

    operations = [
    ]
