# Generated by Django 6.0.2 on 2026-02-17 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260217_1750'),
        ('accounts', '0012_merge_20260217_1806'),
    ]

    operations = [
    ]
