# Generated by Django 6.0.2 on 2026-02-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260217_2257'),
        ('accounts', '0013_merge_20260217_1819'),
    ]

    operations = [
    ]
