# Generated by Django 6.0.2 on 2026-02-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20260218_0118'),
        ('accounts', '0014_merge_20260217_1841'),
    ]

    operations = [
    ]
