# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_merge_20260217_1841"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hide_email_from_employers",
            field=models.BooleanField(default=False),
        ),
    ]
