# Generated by Django 6.0.2 on 2026-02-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20260218_0132'),
        ('accounts', '0015_profile_hide_email_from_employers'),
    ]

    operations = [
    ]
