# Generated by Django 6.0.2 on 2026-02-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20260217_2340'),
        ('accounts', '0016_merge_20260217_2055'),
    ]

    operations = [
    ]
