# Generated by Django 6.0.2 on 2026-02-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260217_2206'),
        ('accounts', '0016_merge_20260217_2055'),
    ]

    operations = [
    ]
