# Generated by Django 6.0.2 on 2026-02-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20260218_1604'),
        ('accounts', '0017_merge_20260218_1635'),
    ]

    operations = [
    ]
