# Generated by Django 6.0.2 on 2026-02-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20260218_1933'),
        ('accounts', '0018_merge_20260218_1741'),
    ]

    operations = [
    ]
