# Generated by Django 6.0.2 on 2026-02-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_profile_company_culture_profile_company_perks"),
    ]

    operations = [
    ]
