# Generated by Django 6.0.2 on 2026-03-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_company_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
