# Generated by Django 6.0.2 on 2026-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_profile_company_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parsed_resume_skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
