# Generated by Django 6.0.2 on 2026-03-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_profile_parsed_resume_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parsed_resume_skills',
            field=models.TextField(blank=True),
        ),
    ]
