# Generated by Django 6.0.2 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_profile_parsed_resume_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcandidatesearch",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
