# Generated by Django 6.0.2 on 2026-03-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_savedcandidatesearch_last_viewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcandidatesearch",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
