"""
Django settings for project2 project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv_file(path):
    values = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


_DOTENV_VALUES = _load_dotenv_file(BASE_DIR / ".env")


def _env(key, default=""):
    if key in _DOTENV_VALUES:
        return _DOTENV_VALUES[key]
    return os.getenv(key, default)


def _csv_env_list(key, default=""):
    raw = _env(key, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+z*$czjy+qza6+nog8@p^22s4mr&nxca@r1t^hq$g8&hksx*m#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = _csv_env_list(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
)

CSRF_TRUSTED_ORIGINS = _csv_env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1:8000,http://localhost:8000"
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'home',
    'accounts',
    'apply',
    'jobposts',
    'map',
    'chatbot',
    'messaging',
    'interviews',
    'pulses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.UpdateLastActivityMiddleware',
]

OPENROUTER_API_KEY = _env('OPENROUTER_API_KEY', '').strip()

ROOT_URLCONF = 'project2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'project2/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.can_post_job',
            ],
        },
    },
]

WSGI_APPLICATION = 'project2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'project2' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration.
smtp_backend = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = _env('EMAIL_BACKEND', '').strip()
if not EMAIL_BACKEND:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' if DEBUG else smtp_backend

EMAIL_HOST = _env('EMAIL_HOST', 'smtp.gmail.com').strip()
EMAIL_PORT = int(_env('EMAIL_PORT', '587'))
EMAIL_HOST_USER = _env('EMAIL_HOST_USER', 'pandapulse.donotreply@gmail.com').strip()
raw_google_app_password = _env('GOOGLE_APP_PASSWORD', '').strip()
raw_email_password = _env('EMAIL_HOST_PASSWORD', '').strip()
EMAIL_HOST_PASSWORD = (raw_google_app_password or raw_email_password).replace(' ', '').replace('-', '')
EMAIL_USE_TLS = _env('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = _env('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_TIMEOUT = int(_env('EMAIL_TIMEOUT', '20'))
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER).strip()
GOOGLE_MAPS_API_KEY = _env('GOOGLE_MAPS_API_KEY', '').strip()

_placeholder_users = {'example@gmail.com', 'your-email@gmail.com'}
_placeholder_passwords = {'abcdabcdabcdabcd', 'yourapppassword', 'changeme'}
if (
    DEBUG
    and EMAIL_BACKEND == smtp_backend
    and (
        not EMAIL_HOST_USER
        or not EMAIL_HOST_PASSWORD
        or EMAIL_HOST_USER.lower() in _placeholder_users
        or EMAIL_HOST_PASSWORD.lower() in _placeholder_passwords
    )
):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

if not DEBUG and EMAIL_BACKEND == smtp_backend and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD):
    raise ImproperlyConfigured(
        "SMTP email requires EMAIL_HOST_USER and EMAIL_HOST_PASSWORD (or GOOGLE_APP_PASSWORD)."
    )








