# Generated by Django 6.0.2 on 2026-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0004_jobpost_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
