# Generated by Django 6.0.2 on 2026-02-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobposts", "0006_alter_jobpost_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("small", "Small (1-50)"),
                    ("mid_size", "Mid-size (51-500)"),
                    ("large", "Large (501-5,000)"),
                    ("fortune_500", "Fortune 500"),
                    ("startup", "Startup"),
                    ("enterprise", "Enterprise"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
