from django.conf import settings
from django.db import models


class ChatFeedback(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="chatbot_feedback",
    )
    user_query = models.TextField(help_text="The last message sent by the user.")
    ai_response = models.TextField(help_text="The response generated by the AI.")
    is_positive = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Chat Feedback"
        ordering = ["-created_at"]

    def __str__(self):
        sentiment = "Positive" if self.is_positive else "Negative"
        return f"{self.user.username} - {sentiment} ({self.created_at:%Y-%m-%d})"
