from django.db import models
from django.conf import settings

class ChatFeedback(models.Model):
    """
    Stores feedback from users regarding the Panda Assistant's responses.
    This helps in auditing the AI's performance and improving prompts.
    """
    # Links to the user who gave the feedback
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
        related_name='chatbot_feedback'
    )
    
    # Stores the text exchanged to provide context for the feedback
    user_query = models.TextField(help_text="The last message sent by the user.")
    ai_response = models.TextField(help_text="The response generated by the AI.")
    
    # Rating: True for Thumbs Up, False for Thumbs Down
    is_positive = models.BooleanField(default=True)
    
    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Chat Feedback"
        ordering = ['-created_at']

    def __str__(self):
        sentiment = "Positive" if self.is_positive else "Negative"
        return f"{self.user.username} - {sentiment} ({self.created_at.strftime('%Y-%m-%d')})"