# Generated by Django 6.0.2 on 2026-03-11 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.PositiveSmallIntegerField()),
                ('communication_score', models.PositiveSmallIntegerField()),
                ('problem_solving_score', models.PositiveSmallIntegerField()),
                ('recommendation', models.CharField(choices=[('advance', 'Advance'), ('hold', 'Hold'), ('reject', 'Reject')], max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('decision_rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback_entries', to=settings.AUTH_USER_MODEL)),
                ('interview_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.interviewslot')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
