# Generated by Django 6.0.2 on 2026-03-11 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSkillEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=120)),
                ('skill_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('endorsed_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_skill_endorsements_received', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_skill_endorsements_given', to=settings.AUTH_USER_MODEL)),
                ('interview_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_endorsements', to='interviews.interviewslot')),
            ],
            options={
                'ordering': ['-endorsed_at'],
                'constraints': [models.UniqueConstraint(fields=('interview_slot', 'skill_key'), name='unique_interview_slot_skill_endorsement')],
            },
        ),
    ]
